### ISSUE TITLE
Debug Failure. Unhandled SyntaxKind: Unknown

### ISSUE THREAD

**Issue by alex-statsig** [sachinraja/zod-to-ts#46]
Getting this error when using with typescript 5.2.2:

```
      "message": "Debug Failure. Unhandled SyntaxKind: Unknown.",
      "stack":
          Error: Debug Failure. Unhandled SyntaxKind: Unknown.
              at pipelineEmitWithHintWorker (/Users/alex/dev/statsig/node_modules/.pnpm/typescript@5.2.2/node_modules/typescript/lib/typescript.js:113284:13)
              at pipelineEmitWithHint (/Users/alex/dev/statsig/node_modules/.pnpm/typescript@5.2.2/node_modules/typescript/lib/typescript.js:112828:9)
              at pipelineEmitWithComments (/Users/alex/dev/statsig/node_modules/.pnpm/typescript@5.2.2/node_modules/typescript/lib/typescript.js:116619:7)
              at pipelineEmit (/Users/alex/dev/statsig/node_modules/.pnpm/typescript@5.2.2/node_modules/typescript/lib/typescript.js:112777:7)
              at emit (/Users/alex/dev/statsig/node_modules/.pnpm/typescript@5.2.2/node_modules/typescript/lib/typescript.js:112745:7)
              at emitTypeAnnotation (/Users/alex/dev/statsig/node_modules/.pnpm/typescript@5.2.2/node_modules/typescript/lib/typescript.js:115569:9)
              at emitIndexSignature (/Users/alex/dev/statsig/node_modules/.pnpm/typescript@5.2.2/node_modules/typescript/lib/typescript.js:113613:7)
              at pipelineEmitWithHintWorker (/Users/alex/dev/statsig/node_modules/.pnpm/typescript@5.2.2/node_modules/typescript/lib/typescript.js:112903:20)
              at pipelineEmitWithHint (/Users/alex/dev/statsig/node_modules/.pnpm/typescript@5.2.2/node_modules/typescript/lib/typescript.js:112828:9)
              at pipelineEmitWithComments (/Users/alex/dev/statsig/node_modules/.pnpm/typescript@5.2.2/node_modules/typescript/lib/typescript.js:116619:7)
              at pipelineEmit (/Users/alex/dev/statsig/node_modules/.pnpm/typescript@5.2.2/node_modules/typescript/lib/typescript.js:112777:7)
              at emit (/Users/alex/dev/statsig/node_modules/.pnpm/typescript@5.2.2/node_modules/typescript/lib/typescript.js:112745:7)
              at emitListItemWithParenthesizerRule (/Users/alex/dev/statsig/node_modules/.pnpm/typescript@5.2.2/node_modules/typescript/lib/typescript.js:117065:5)
              at emitNodeListItems (/Users/alex/dev/statsig/node_modules/.pnpm/typescript@5.2.2/node_modules/typescript/lib/typescript.js:115776:9)
              at emitNodeList (/Users/alex/dev/statsig/node_modules/.pnpm/typescript@5.2.2/node_modules/typescript/lib/typescript.js:115715:9)
              at emitList (/Users/alex/dev/statsig/node_modules/.pnpm/typescript@5.2.2/node_modules/typescript/lib/typescript.js:115673:7)
              at emitTypeLiteral (/Users/alex/dev/statsig/node_modules/.pnpm/typescript@5.2.2/node_modules/typescript/lib/typescript.js:113695:7)
              at pipelineEmitWithHintWorker (/Users/alex/dev/statsig/node_modules/.pnpm/typescript@5.2.2/node_modules/typescript/lib/typescript.js:112915:20)
              at pipelineEmitWithHint (/Users/alex/dev/statsig/node_modules/.pnpm/typescript@5.2.2/node_modules/typescript/lib/typescript.js:112828:9)
              at pipelineEmitWithComments (/Users/alex/dev/statsig/node_modules/.pnpm/typescript@5.2.2/node_modules/typescript/lib/typescript.js:116619:7)
              at pipelineEmit (/Users/alex/dev/statsig/node_modules/.pnpm/typescript@5.2.2/node_modules/typescript/lib/typescript.js:112777:7)
              at emit (/Users/alex/dev/statsig/node_modules/.pnpm/typescript@5.2.2/node_modules/typescript/lib/typescript.js:112745:7)
              at emitListItemWithParenthesizerRule (/Users/alex/dev/statsig/node_modules/.pnpm/typescript@5.2.2/node_modules/typescript/lib/typescript.js:117065:5)
              at emitNodeListItems (/Users/alex/dev/statsig/node_modules/.pnpm/typescript@5.2.2/node_modules/typescript/lib/typescript.js:115776:9)
              at emitNodeList (/Users/alex/dev/statsig/node_modules/.pnpm/typescript@5.2.2/node_modules/typescript/lib/typescript.js:115715:9)
              at emitList (/Users/alex/dev/statsig/node_modules/.pnpm/typescript@5.2.2/node_modules/typescript/lib/typescript.js:115673:7)
              at emitUnionType (/Users/alex/dev/statsig/node_modules/.pnpm/typescript@5.2.2/node_modules/typescript/lib/typescript.js:113727:7)
              at pipelineEmitWithHintWorker (/Users/alex/dev/statsig/node_modules/.pnpm/typescript@5.2.2/node_modules/typescript/lib/typescript.js:112923:20)
              at pipelineEmitWithHint (/Users/alex/dev/statsig/node_modules/.pnpm/typescript@5.2.2/node_modules/typescript/lib/typescript.js:112828:9)
              at pipelineEmitWithComments (/Users/alex/dev/statsig/node_modules/.pnpm/typescript@5.2.2/node_modules/typescript/lib/typescript.js:116619:7)
              at pipelineEmit (/Users/alex/dev/statsig/node_modules/.pnpm/typescript@5.2.2/node_modules/typescript/lib/typescript.js:112777:7)
              at print (/Users/alex/dev/statsig/node_modules/.pnpm/typescript@5.2.2/node_modules/typescript/lib/typescript.js:112690:7)
              at writeNode (/Users/alex/dev/statsig/node_modules/.pnpm/typescript@5.2.2/node_modules/typescript/lib/typescript.js:112533:7)
              at Object.printNode (/Users/alex/dev/statsig/node_modules/.pnpm/typescript@5.2.2/node_modules/typescript/lib/typescript.js:112497:7)
              at printNode (/Users/alex/dev/statsig/node_modules/.pnpm/zod-to-ts@1.1.1_pkihvv7tkirfyj5v6rn4ddr4b4/node_modules/zod-to-ts/dist/index.cjs:42:18)
```

This happened when calling `printNode(zodToTs(z.record(z.unknown())).node)` and other records (ex. `z.record(z.string(), z.string()).optional()`)

**Comment by sachinraja** [comment]
I believe this works now in [v2.0.0](https://www.npmjs.com/package/zod-to-ts/v/2.0.0)
